#!/usr/bin/with-contenv bash

echo "Setting fpm user to nginx"
sed -i 's/.*listen.owner = .*/listen.owner = nginx/g' /etc/php7/php-fpm.d/www.conf   
sed -i 's/.*listen.group = .*/listen.group = nginx/g' /etc/php7/php-fpm.d/www.conf   
